### ISSUE TITLE
Passport makes http error when calling passport

### ISSUE THREAD

**Issue by Anismash** [PaddoInWonderland/PaddoCogs#15]
Ignoring exception in message_delete
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/root/Red-DiscordBot/cogs/grenzpolizei.py", line 209, in _on_message_delete
    await self.bot.send_message(customs_channel, embed=em)
  File "red.py", line 75, in send_message
    return await super().send_message(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

**Comment by PaddoInWonderland** [comment]
Not relevant anymore.
